theme: minima

title: "Inuit Crochet"
description: Vous trouverez sur ce blog des liens vers mes travaux, des conseils et les patrons que j'ai rédigé

minima:
  skin: dark
  social_links:
    - { platform: mastodon,  user_url: "https://pouet.chapril.org/@pierrobn" }
    - { platform: github, user_url: "https://github.com/pbnPierre" }
    - { platform: instagram, user_url: "https://www.instagram.com/inuit_crochet" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/pierre-bertrand-787b9288" }

markdown: kramdown

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - patterns/Ariane5/Ariane5.md
  - patterns/Ariane6/Ariane6.md
  - patterns/VegaC/VegaC.md
  - patterns/FalconHeavy/FalconHeavy.md
  - patterns/Movember/Moustache.md
  - patterns/CaitSith/CaitSith.md
