theme: minima

minima:
  skin: dark

markdown: kramdown
title: Inuit Crochet
description: Vous trouverez sur ce blog des liens vers mes travaux, des conseils et les patrons que j'ai rédigé
favicon:
  source: media/favicon.png


plugins:
  - jekyll-seo-tag
  - jekyll-favicon
  - jekyll-remote-theme

social:
  name: Pierre B aka Inuit Crochet
  links:
    - https://www.instagram.com/inuit_crochet
    - https://pouet.chapril.org/@pierrobn
    - https://buymeacoffee.com/inuitcrochet


header_pages:
  - patterns/Ariane5/Ariane5.md
  - patterns/Ariane6/Ariane6.md
  - patterns/VegaC/VegaC.md
  - patterns/FalconHeavy/FalconHeavy.md
  - patterns/Movember/Moustache.md
  - patterns/CaitSith/CaitSith.md
