theme: minima
markdown: kramdown
title: Inuit Crochet
description: Vous trouverez sur ce blog des liens vers mes travaux, des conseils et les patrons que j'ai rédigé
favicon:
  source: media/favicon.png


plugins:
  - jekyll-seo-tag
  - jekyll-favicon

social:
  name: Pierre B aka Inuit Crochet
  links:
    - https://www.instagram.com/inuit_crochet
    - https://pouet.chapril.org/@pierrobn
    - https://buymeacoffee.com/inuitcrochet

