theme: jekyll-theme-minimal
markdown: kramdown
title: Le blog de Pierre B sur le crochet. De son petit nom Inuit Crochet
description: Vous trouverez sur ce blog des liens vers mes travaux, des conseils et les patrons que j'ai rédigés